version: '3'

services:
  sqlite:
    build:
      context: ./SQLite
      dockerfile: Dockerfile
    volumes:
      - sqlite-data:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - sqlite-data:/data
    environment:
      - SQLITE_DB_PATH=/data/database.sqlite
      - USER=${USER}
    depends_on:
      - sqlite

volumes:
  sqlite-data:
    driver: local